package github

import (
	"context"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	gogithub "github.com/google/go-github/v69/github"
)

const maxPatchLines = 200

// prURLPattern matches a GitHub PR URL and captures owner, repo, and PR number.
// Accepts variants with or without trailing slash, query strings, or anchors.
var prURLPattern = regexp.MustCompile(`^https?://github\.com/([^/]+)/([^/]+)/pull/(\d+)(?:[/?#].*)?$`)

// CodeRabbit "Change Impact" parsing.
//
// CodeRabbit injects a Change Impact section into the PR DESCRIPTION
// (pr.body), wrapped in HTML comment delimiters. Two real-world shapes:
//
// PR #36300 (with italicized footer):
//   <!-- This is an auto-generated comment: release notes by coderabbit.ai -->
//   ## Change Impact: 🟠 Medium
//   **Regression Risk:** Adds new optional fields...
//   **QA Recommendation:** Moderate manual QA...
//   *Generated by CodeRabbitAI*
//   <!-- end of auto-generated comment: release notes by coderabbit.ai -->
//
// PR #36346 (no italicized footer, just HTML comment markers + a `---`
// then a Release Notes block):
//   <!-- This is an auto-generated comment: release notes by coderabbit.ai -->
//   ## Change Impact: 🟢 Low
//   **Regression Risk:** Minimal. ...
//   **QA Recommendation:** Manual QA is optional. ...
//   ---
//   **Release Notes:** ...
//   <!-- end of auto-generated comment: release notes by coderabbit.ai -->
//
// Detection: body contains "coderabbit" (case-insensitive) — both shapes
// share the HTML comment markers. We don't require the italicized
// "Generated by CodeRabbitAI" string because not all CodeRabbit posts
// include it.
//
// The Change Impact line may be a markdown heading (`##`), bold (`**`),
// or plain. Section terminators include the next labeled section, the
// optional italicized footer, the closing HTML comment, and a `---`
// horizontal rule (which separates the Change Impact block from any
// Release Notes block in PR #36346's shape).
var (
	codeRabbitChangeImpactRe = regexp.MustCompile(`(?m)^[#*\s]*Change Impact\s*:?\s*\**\s*(.+?)\s*$`)
	codeRabbitRegressionRe   = regexp.MustCompile(`(?ms)[*_]*Regression Risk[*_]*\s*:?\s*[*_]*\s*(.+?)(?:\n\s*[*_]*\s*QA Recommendation\s*:?|Generated by CodeRabbitAI|\n\s*---|<!--\s*end of auto-generated|\z)`)
	codeRabbitQARe           = regexp.MustCompile(`(?ms)[*_]*QA Recommendation[*_]*\s*:?\s*[*_]*\s*(.+?)(?:Generated by CodeRabbitAI|\n\s*---|<!--\s*end of auto-generated|\z)`)
)

// parseCodeRabbitImpact extracts the tier (HIGH/MEDIUM/LOW), Regression Risk
// paragraph, and QA Recommendation paragraph from a CodeRabbit comment body.
// Returns ok=false if the body doesn't match the CodeRabbit shape.
func parseCodeRabbitImpact(body string) (tier, regression, qa string, ok bool) {
	// Detection: body must mention coderabbit (typically via the HTML
	// comment markers like "auto-generated comment ... coderabbit.ai")
	// AND contain a parseable Change Impact line.
	if !strings.Contains(strings.ToLower(body), "coderabbit") {
		return "", "", "", false
	}
	impactMatch := codeRabbitChangeImpactRe.FindStringSubmatch(body)
	if impactMatch == nil {
		return "", "", "", false
	}
	tier = parseCodeRabbitTier(impactMatch[1])
	if tier == "" {
		return "", "", "", false
	}

	if m := codeRabbitRegressionRe.FindStringSubmatch(body); m != nil {
		regression = trimMarkdown(m[1])
	}
	if m := codeRabbitQARe.FindStringSubmatch(body); m != nil {
		qa = trimMarkdown(m[1])
	}
	return tier, regression, qa, true
}

// trimMarkdown strips trailing whitespace plus dangling markdown emphasis
// characters (`*` / `_`) that can leak in when a section is followed by an
// italic/bold footer (e.g. `*Generated by CodeRabbitAI*`).
func trimMarkdown(s string) string {
	return strings.TrimRight(strings.TrimSpace(s), "*_ \t\r\n")
}

// parseCodeRabbitTier maps the right-hand side of `Change Impact:` to a
// canonical tier. Accepts emoji (🔴/🟠/🟢) and English words.
func parseCodeRabbitTier(s string) string {
	lower := strings.ToLower(s)
	switch {
	case strings.Contains(s, "🔴") || strings.Contains(lower, "critical") || strings.Contains(lower, "high"):
		return "HIGH"
	case strings.Contains(s, "🟠") || strings.Contains(s, "🟡") || strings.Contains(lower, "medium") || strings.Contains(lower, "moderate"):
		return "MEDIUM"
	case strings.Contains(s, "🟢") || strings.Contains(lower, "low") || strings.Contains(lower, "minimal"):
		return "LOW"
	default:
		return ""
	}
}

// ParsePRURL extracts owner, repo, and PR number from a GitHub PR URL.
// Returns an error if the URL doesn't match the expected shape.
func ParsePRURL(prURL string) (owner, repo string, number int, err error) {
	prURL = strings.TrimSpace(prURL)
	matches := prURLPattern.FindStringSubmatch(prURL)
	if matches == nil {
		return "", "", 0, fmt.Errorf("invalid GitHub PR URL %q — expected https://github.com/OWNER/REPO/pull/NUMBER", prURL)
	}
	num, err := strconv.Atoi(matches[3])
	if err != nil {
		return "", "", 0, fmt.Errorf("invalid PR number in URL %q: %w", prURL, err)
	}
	return matches[1], matches[2], num, nil
}

// FetchSinglePR fetches one PR by URL, bypassing the team/author/date filters
// used by FetchPRs. Returns a FetchResult with exactly one PRData on success.
// When fetchCodeRabbit is true, the PR's issue comments are also pulled and
// any CodeRabbit Change Impact summary is parsed onto the result.
func FetchSinglePR(ctx context.Context, client *Client, prURL string, fetchCodeRabbit bool) (*FetchResult, error) {
	owner, repo, number, err := ParsePRURL(prURL)
	if err != nil {
		return nil, err
	}

	fmt.Fprintf(client.Log(), "[fetch] Single PR mode: %s/%s#%d\n", owner, repo, number)

	pr, _, err := client.GetPullRequest(ctx, owner, repo, number)
	if err != nil {
		return nil, fmt.Errorf("fetching PR %s/%s#%d: %w", owner, repo, number, err)
	}

	prData, err := buildPRData(ctx, client, owner, repo, pr, fetchCodeRabbit)
	if err != nil {
		return nil, err
	}

	fmt.Fprintf(client.Log(), "[api] Total API calls: %d | Rate limit remaining: %d\n",
		client.APICallsMade(), client.RateRemaining())

	return &FetchResult{
		PRs:           []PRData{*prData},
		APICallsMade:  client.APICallsMade(),
		RateRemaining: client.RateRemaining(),
	}, nil
}

func FetchPRs(ctx context.Context, client *Client, opts FetchOptions) (*FetchResult, error) {
	var allPRs []PRData

	for _, repoFullName := range opts.Repos {
		parts := strings.SplitN(repoFullName, "/", 2)
		if len(parts) != 2 {
			return nil, fmt.Errorf("invalid repo format %q — expected owner/name", repoFullName)
		}
		owner, repo := parts[0], parts[1]

		prs, err := fetchRepoPRs(ctx, client, owner, repo, opts)
		if err != nil {
			return nil, fmt.Errorf("fetching %s: %w", repoFullName, err)
		}
		allPRs = append(allPRs, prs...)
	}

	fmt.Fprintf(client.Log(), "[api] Total API calls: %d | Rate limit remaining: %d\n",
		client.APICallsMade(), client.RateRemaining())

	return &FetchResult{
		PRs:           allPRs,
		APICallsMade:  client.APICallsMade(),
		RateRemaining: client.RateRemaining(),
	}, nil
}

func fetchRepoPRs(ctx context.Context, client *Client, owner, repo string, opts FetchOptions) ([]PRData, error) {
	repoFullName := owner + "/" + repo
	authorSet := make(map[string]bool)
	for _, a := range opts.Authors {
		authorSet[strings.ToLower(a)] = true
	}

	listOpts := &gogithub.PullRequestListOptions{
		State:     "all",
		Sort:      "updated",
		Direction: "desc",
		ListOptions: gogithub.ListOptions{
			PerPage: 100,
		},
	}

	fmt.Fprintf(client.Log(), "[fetch] %s — scanning PRs for authors: %v — since: %s\n",
		repoFullName, opts.Authors, opts.Since.Format("2006-01-02"))

	var matchedPRs []*gogithub.PullRequest

	for {
		prs, resp, err := client.ListPullRequests(ctx, owner, repo, listOpts)
		if err != nil {
			return nil, fmt.Errorf("listing PRs for %s: %w", repoFullName, err)
		}

		stoppedEarly := false
		for _, pr := range prs {
			updated := pr.GetUpdatedAt().Time
			if updated.Before(opts.Since) {
				stoppedEarly = true
				break
			}

			prAuthor := strings.ToLower(pr.GetUser().GetLogin())
			if !authorSet[prAuthor] {
				continue
			}

			created := pr.GetCreatedAt().Time
			if created.Before(opts.Since) && updated.Before(opts.Since) {
				continue
			}

			matchedPRs = append(matchedPRs, pr)
		}

		if stoppedEarly || resp.NextPage == 0 {
			break
		}
		listOpts.Page = resp.NextPage
	}

	fmt.Fprintf(client.Log(), "[fetch] %s — %d PRs matched\n", repoFullName, len(matchedPRs))

	var allPRs []PRData
	for _, pr := range matchedPRs {
		prData, err := buildPRData(ctx, client, owner, repo, pr, opts.FetchCodeRabbit)
		if err != nil {
			return nil, err
		}
		allPRs = append(allPRs, *prData)
	}

	return allPRs, nil
}

func buildPRData(ctx context.Context, client *Client, owner, repo string, pr *gogithub.PullRequest, fetchCodeRabbit bool) (*PRData, error) {
	repoFullName := owner + "/" + repo
	prNumber := pr.GetNumber()

	fmt.Fprintf(client.Log(), "[fetch] %s — PR #%d: %s\n", repoFullName, prNumber, pr.GetTitle())

	var allFiles []*gogithub.CommitFile
	fileOpts := &gogithub.ListOptions{PerPage: 100}
	for {
		files, resp, err := client.ListPRFiles(ctx, owner, repo, prNumber, fileOpts)
		if err != nil {
			return nil, fmt.Errorf("listing files for PR #%d in %s: %w", prNumber, repoFullName, err)
		}
		allFiles = append(allFiles, files...)
		if resp.NextPage == 0 {
			break
		}
		fileOpts.Page = resp.NextPage
	}

	var fileDiffs []FileDiff
	totalAdditions, totalDeletions := 0, 0

	for _, f := range allFiles {
		patch := f.GetPatch()
		truncated := false

		if lines := strings.Count(patch, "\n"); lines > maxPatchLines {
			patchLines := strings.SplitN(patch, "\n", maxPatchLines+1)
			patch = strings.Join(patchLines[:maxPatchLines], "\n")
			truncated = true
		}

		fileDiffs = append(fileDiffs, FileDiff{
			Filename:  f.GetFilename(),
			Status:    f.GetStatus(),
			Additions: f.GetAdditions(),
			Deletions: f.GetDeletions(),
			Patch:     patch,
			Truncated: truncated,
		})

		totalAdditions += f.GetAdditions()
		totalDeletions += f.GetDeletions()
	}

	state := pr.GetState()
	if pr.GetMerged() || !pr.GetMergedAt().IsZero() {
		state = "merged"
	}

	blast := computeBlastRadius(fileDiffs, totalAdditions+totalDeletions)
	approvers := fetchApprovers(ctx, client, owner, repo, prNumber)

	var crTier, crReason, crQA string
	if fetchCodeRabbit {
		if t, r, q, ok := parseCodeRabbitImpact(pr.GetBody()); ok {
			crTier, crReason, crQA = t, r, q
			fmt.Fprintf(client.Log(), "[fetch] %s — PR #%d: CodeRabbit %s (from PR body)\n", repoFullName, prNumber, t)
		} else {
			fmt.Fprintf(client.Log(), "[fetch] %s — PR #%d: no CodeRabbit Change Impact in PR body, will analyze with agent\n", repoFullName, prNumber)
		}
	}

	return &PRData{
		PRNumber:    prNumber,
		PRState:     state,
		PRURL:       pr.GetHTMLURL(),
		Title:       pr.GetTitle(),
		Author:      pr.GetUser().GetLogin(),
		Repo:        repoFullName,
		HeadSHA:     pr.GetHead().GetSHA(),
		Date:        pr.GetCreatedAt().Time,
		Stats: PRStats{
			Additions: totalAdditions,
			Deletions: totalDeletions,
			Total:     totalAdditions + totalDeletions,
		},
		BlastRadius:      blast,
		Approvers:        approvers,
		Files:            fileDiffs,
		CodeRabbitImpact: crTier,
		CodeRabbitReason: crReason,
		CodeRabbitQA:     crQA,
	}, nil
}

func fetchApprovers(ctx context.Context, client *Client, owner, repo string, prNumber int) []string {
	var approvers []string
	seen := make(map[string]bool)

	opts := &gogithub.ListOptions{PerPage: 100}
	for {
		reviews, resp, err := client.ListReviews(ctx, owner, repo, prNumber, opts)
		if err != nil {
			break
		}
		for _, r := range reviews {
			if r.GetState() == "APPROVED" {
				login := r.GetUser().GetLogin()
				if login != "" && !seen[login] {
					seen[login] = true
					approvers = append(approvers, login)
				}
			}
		}
		if resp.NextPage == 0 {
			break
		}
		opts.Page = resp.NextPage
	}

	return approvers
}

func computeBlastRadius(files []FileDiff, totalLines int) BlastRadius {
	dirSet := make(map[string]bool)
	areaSet := make(map[string]bool)

	for _, f := range files {
		parts := strings.Split(f.Filename, "/")
		if len(parts) > 1 {
			dirSet[strings.Join(parts[:len(parts)-1], "/")] = true
		}
		area := classifyArea(f.Filename)
		if area != "" {
			areaSet[area] = true
		}
	}

	var areas []string
	for a := range areaSet {
		areas = append(areas, a)
	}

	return BlastRadius{
		FilesChanged:  len(files),
		DirsChanged:   len(dirSet),
		AreasAffected: areas,
		TotalLines:    totalLines,
		CrossArea:     len(areaSet) > 1,
	}
}

func classifyArea(filename string) string {
	lower := strings.ToLower(filename)
	switch {
	case strings.HasPrefix(lower, "server/"):
		return "server"
	case strings.HasPrefix(lower, "webapp/"):
		return "webapp"
	case strings.HasPrefix(lower, "e2e-tests/") || strings.HasSuffix(lower, "_test.go") || strings.HasSuffix(lower, ".spec.ts"):
		return "tests"
	case strings.HasPrefix(lower, "mobile/") || strings.HasPrefix(lower, "ios/") || strings.HasPrefix(lower, "android/") || strings.HasPrefix(lower, "app/") || strings.HasPrefix(lower, "libraries/"):
		return "mobile"
	case strings.HasPrefix(lower, "plugin/") || strings.Contains(lower, "hook"):
		return "plugin"
	case strings.HasPrefix(lower, "docker") || strings.HasPrefix(lower, ".github/") || lower == "makefile" || strings.HasSuffix(lower, ".yml") || strings.HasSuffix(lower, ".yaml"):
		return "infra"
	case strings.HasSuffix(lower, ".sql") || strings.Contains(lower, "migration"):
		return "database"
	default:
		return ""
	}
}
